//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xa11ytaire {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xa11ytaire.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace.
        /// </summary>
        internal static string Ace {
            get {
                return ResourceManager.GetString("Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        internal static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs pile.
        /// </summary>
        internal static string ClubsPile {
            get {
                return ResourceManager.GetString("ClubsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds.
        /// </summary>
        internal static string Diamonds {
            get {
                return ResourceManager.GetString("Diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds pile.
        /// </summary>
        internal static string DiamondsPile {
            get {
                return ResourceManager.GetString("DiamondsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty slot.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a king can be placed here..
        /// </summary>
        internal static string EmptyCardHelpText {
            get {
                return ResourceManager.GetString("EmptyCardHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restack remaining cards.
        /// </summary>
        internal static string EmptyNextCard {
            get {
                return ResourceManager.GetString("EmptyNextCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face down.
        /// </summary>
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game restarted.
        /// </summary>
        internal static string GameRestarted {
            get {
                return ResourceManager.GetString("GameRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        internal static string Hearts {
            get {
                return ResourceManager.GetString("Hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts pile.
        /// </summary>
        internal static string HeartsPile {
            get {
                return ResourceManager.GetString("HeartsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in dealt card pile.
        /// </summary>
        internal static string InDealtCardPile {
            get {
                return ResourceManager.GetString("InDealtCardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        internal static string Jack {
            get {
                return ResourceManager.GetString("Jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next cards.
        /// </summary>
        internal static string NextCard {
            get {
                return ResourceManager.GetString("NextCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stacked cards left..
        /// </summary>
        internal static string NoCardLeft {
            get {
                return ResourceManager.GetString("NoCardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on top.
        /// </summary>
        internal static string OnTop {
            get {
                return ResourceManager.GetString("OnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pile.
        /// </summary>
        internal static string Pile {
            get {
                return ResourceManager.GetString("Pile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 1.
        /// </summary>
        internal static string Pile1 {
            get {
                return ResourceManager.GetString("Pile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 2.
        /// </summary>
        internal static string Pile2 {
            get {
                return ResourceManager.GetString("Pile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 3.
        /// </summary>
        internal static string Pile3 {
            get {
                return ResourceManager.GetString("Pile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 4.
        /// </summary>
        internal static string Pile4 {
            get {
                return ResourceManager.GetString("Pile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 5.
        /// </summary>
        internal static string Pile5 {
            get {
                return ResourceManager.GetString("Pile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 6.
        /// </summary>
        internal static string Pile6 {
            get {
                return ResourceManager.GetString("Pile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 7.
        /// </summary>
        internal static string Pile7 {
            get {
                return ResourceManager.GetString("Pile7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restacked remaining cards.
        /// </summary>
        internal static string RestackedCards {
            get {
                return ResourceManager.GetString("RestackedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revealed.
        /// </summary>
        internal static string Revealed {
            get {
                return ResourceManager.GetString("Revealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades.
        /// </summary>
        internal static string Spades {
            get {
                return ResourceManager.GetString("Spades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades pile.
        /// </summary>
        internal static string SpadesPile {
            get {
                return ResourceManager.GetString("SpadesPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upturned.
        /// </summary>
        internal static string Upturned {
            get {
                return ResourceManager.GetString("Upturned", resourceCulture);
            }
        }
    }
}
